### ISSUE TITLE
Date controls problems

### ISSUE THREAD

**Issue by RokLenarcic** [fulcrologic/fulcro-rad-semantic-ui#18]
I've tried adding two type `:instant` controls to add `from:` and `to:` time based filtering to a report.

```
::m.job/from {:type :instant :label "From:" :style :starting-date :onChange (fn [instance v] (control/run! instance))}
::m.job/to {:type :instant :label "To:" :style :ending-date :onChange (fn [instance v] (control/run! instance))}
```
I've used `:starting-date` and `:ending-date` style for these controls because that seemed to make sense for such a filter control.

I've encountered three problems. When I navigate to report, the initial state of these controls is like this:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/3322433/139931774-2dc49833-9586-4970-b631-5e6cf1bb46b6.png">

First thing is that the dates seem very confusing. Today is 2nd of november and the default `from` date looks to be after the `to` date. It seems weird.

The second problem is that the controls start initialized to today. This makes their use in report filtering awkward, because usually you want to start without the filter, where-as here the filter makes sure that there is 0 rows left. To see any rows, the user must first unset these controls when they enter the report.

The third problem is that the values cannot be unset. If I click the control and click `Clear` button, I get this error in JS console:

```
js-joda.js:6244 Uncaught E {message: "Text '' could not be parsed at index 0: , at index: 0", stack: "DateTimeParseException: Text '' could not be parse…ljs-runtime/com.fulcrologic.fulcro.dom.js:504:97)", parsedString: ƒ, errorIndex: ƒ, toString: ƒ}errorIndex: λ[]message: "Text '' could not be parsed at index 0: , at index: 0"parsedString: λ[]toString: λ[]stack: "DateTimeParseException: Text '' could not be parsed at index 0: , at index: 0\n    at DateTimeFormatter._parseToBuilder (http://localhost:3000/js/main/cljs-runtime/module$node_modules$js_joda$dist$js_joda.js:316:261)\n    at DateTimeFormatter.parse2 (http://localhost:3000/js/main/cljs-runtime/module$node_modules$js_joda$dist$js_joda.js:315:25)\n    at DateTimeFormatter.parse (http://localhost:3000/js/main/cljs-runtime/module$node_modules$js_joda$dist$js_joda.js:314:119)\n    at Function.LocalDate.parse (http://localhost:3000/js/main/cljs-runtime/module$node_modules$js_joda$dist$js_joda.js:429:18)\n    at Function.eval [as cljs$core$IFn$_invoke$arity$1] (http://localhost:3000/js/main/cljs-runtime/cljc.java_time.local_date.js:197:28)\n    at eval (http://localhost:3000/js/main/cljs-runtime/com.fulcrologic.rad.type_support.date_time.js:1034:80)\n    at f64405 (http://localhost:3000/js/main/cljs-runtime/com.fulcrologic.rad.type_support.date_time.js:1040:3)\n    at Object.com$fulcrologic$rad$type_support$date_time$html_date__GT_inst [as html_date__GT_inst] (http://localhost:3000/js/main/cljs-runtime/com.fulcrologic.rad.type_support.date_time.js:1044:16)\n    at eval (http://localhost:3000/js/main/cljs-runtime/com.fulcrologic.rad.rendering.semantic_ui.controls.instant_inputs.js:29:58)\n    at ctor.eval [as onChange] (http://localhost:3000/js/main/cljs-runtime/com.fulcrologic.fulcro.dom.js:504:97)"[[Prototype]]: DateTimeParseException
    at createErrorType (http://localhost:3000/js/main/cljs-runtime/module$node_modules$js_joda$dist$js_joda.js:2:85)
    at eval (http://localhost:3000/js/main/cljs-runtime/module$node_modules$js_joda$dist$js_joda.js:41:286)
    at eval (http://localhost:3000/js/main/cljs-runtime/module$node_modules$js_joda$dist$js_joda.js:1:187)
    at Object.shadow$provide.module$node_modules$js_joda$dist$js_joda (http://localhost:3000/js/main/cljs-runtime/module$node_modules$js_joda$dist$js_joda.js:1:298)
    at Object.shadow.js.jsRequire (http://localhost:3000/js/main/cljs-runtime/shadow.js.js:34:18)
    at Object.shadow.js.require (http://localhost:3000/js/main/cljs-runtime/shadow.js.js:59:20)
    at eval (http://localhost:3000/js/main/cljs-runtime/java.time.js:2:56)
    at eval (<anonymous>)
    at Object.goog.globalEval (http://localhost:3000/js/main/main.js:577:21)
    at Object.env.evalLoad (http://localhost:3000/js/main/main.js:1670:12)
DateTimeFormatter.parse2 @ js-joda.js:6244
DateTimeFormatter.parse @ js-joda.js:6219
LocalDate.parse @ js-joda.js:8510
eval @ local_date.cljc:37
eval @ date_time.cljc:330
f64405 @ date_time.cljc:330
com$fulcrologic$rad$type_support$date_time$html_date__GT_inst @ date_time.cljc:328
eval @ instant_inputs.cljc:23
eval @ dom.cljs:167
callCallback @ react-dom.development.js:3946
invokeGuardedCallbackImpl @ react-dom.development.js:3995
invokeGuardedCallback @ react-dom.development.js:4057
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4071
executeDispatch @ react-dom.development.js:8244
processDispatchQueue @ react-dom.development.js:8276
eval @ react-dom.development.js:8300
eval @ react-dom.development.js:22397
batchedEventUpdates @ react-dom.development.js:3746
dispatchEventForPluginEventSystem @ react-dom.development.js:8508
attemptToDispatchEvent @ react-dom.development.js:6006
dispatchEvent @ react-dom.development.js:5925
exports.unstable_runWithPriority @ scheduler.development.js:647
runWithPriority$1 @ react-dom.development.js:11277
Internals.Events @ react-dom.development.js:22414
dispatchDiscreteEvent @ react-dom.development.js:3757
react-dom.development.js:4092 Uncaught E {message: "Text '' could not be parsed at index 0: , at index: 0", stack: "DateTimeParseException: Text '' could not be parse…ljs-runtime/com.fulcrologic.fulcro.dom.js:504:97)", parsedString: ƒ, errorIndex: ƒ, toString: ƒ}
processDispatchQueue @ react-dom.development.js:4092
eval @ react-dom.development.js:8300
eval @ react-dom.development.js:22397
batchedEventUpdates @ react-dom.development.js:3746
dispatchEventForPluginEventSystem @ react-dom.development.js:8508
attemptToDispatchEvent @ react-dom.development.js:6006
dispatchEvent @ react-dom.development.js:5925
exports.unstable_runWithPriority @ scheduler.development.js:647
runWithPriority$1 @ react-dom.development.js:11277
Internals.Events @ react-dom.development.js:22414
dispatchDiscreteEvent @ react-dom.development.js:3757

```
Seems like the component cannot handle empty values.

**Comment by awkay** [comment]
Feel free to send a PR for tweaking things.  You should be able to initialize the dates as you see fit...I would hope the demo showed that, but don't remember if it did.  In terms of clearing the dates, probably just overlooked it.

**Comment by RokLenarcic** [comment]
The code specifically initializes the date fields to now:
https://github.com/fulcrologic/fulcro-rad-semantic-ui/blob/develop/src/main/com/fulcrologic/rad/rendering/semantic_ui/controls/instant_inputs.cljc#L14

https://github.com/fulcrologic/fulcro-rad-semantic-ui/blob/develop/src/main/com/fulcrologic/rad/rendering/semantic_ui/controls/instant_inputs.cljc#L30

https://github.com/fulcrologic/fulcro-rad-semantic-ui/blob/develop/src/main/com/fulcrologic/rad/rendering/semantic_ui/controls/instant_inputs.cljc#L46

The `:starting-date` control also has a flaw where whatever you pick, it instantly is set to one day backward. I think it appears to be working correctly because you have a minus timezone, while I have the positive timezone. 

I am trying to come up with a correct implementation.

**Comment by awkay** [comment]
Did you correctly set YOUR timezone on app startup?

**Comment by RokLenarcic** [comment]
Yes I've set it to UTC+1. So clicking Nov 4th on `:style :starting-date` control will set the value to Nov 4th 00:00 UTC+1, which is then translated to `#inst` which makes the value `#inst "2021-11-03T23:00:00.000-00:00"`, all of this is correct. But then the control renders this into string `03/11/2021` which is kinda correct but also wonky, because I clicked `4` in date picker now it's showing `3` for day of month. 

If you have a negative timezone like `America/Los Angeles` you won't notice this effect.

**Comment by RokLenarcic** [comment]
I'm going to sink some time into improving these date pickers.

**Comment by awkay** [comment]
What version of RAD?  I recently did some work on the timezone support. That formatting function should *shift* the date into the correct local timezone (if you've set it) and display it correctly. There are tests in the library to show this is the case, so you should *not* be seeing what you're seeing. That is a bug...but it may be due to recent changes, or you not having your project set up correctly.

**Comment by RokLenarcic** [comment]
Using the latest SHA

**Comment by awkay** [comment]
So, I still suspect something is wrong in your env. Can you use a CLJS REPL and play with the functions in the date-time ns?  If you set your time zone, then those should do the right thing based on an inst. See the tests in RAD repo.

**Comment by RokLenarcic** [comment]
#19 Fixes a part of it

**Comment by awkay** [comment]
I see you closed your PR. Did you decide not to do it?

**Comment by RokLenarcic** [comment]
That PR did not address the problem. 

The problem is that even if I put `nil` as default value, I will get current date in the input field. And the second problem is that the value in the input field does not reflect the value in the model correctly.

**Comment by awkay** [comment]
I think this is fixed now, right?

**Comment by RokLenarcic** [comment]
Yes
