### ISSUE TITLE
id-child-pairs in container renderer called with wrong values

### ISSUE THREAD

**Issue by eoogbe** [fulcrologic/fulcro-rad-semantic-ui#32]
https://github.com/fulcrologic/fulcro-rad-semantic-ui/blob/a60b9eee33b5ca281e2a982caabb1a227d4bca4d/src/main/com/fulcrologic/rad/rendering/semantic_ui/container.cljc#L85

```diff
(defn render-container-layout [container-instance]
  (let [{::container/keys [children layout]} (comp/component-options container-instance)]
    ;;; ...
-                  (render-cls id cls))) (container/id-child-pairs children))))))))
+                  (render-cls id cls))) (container/id-child-pairs container-instance))))))))
```

Because of this bug, the current implementation does not render anything unless `co/layout` is specified.

**Comment by awkay** [comment]
Fixed in 1.2.19
