### ISSUE TITLE
Rendering glitches in form ToOnePicker

### ISSUE THREAD

**Issue by danskarda** [fulcrologic/fulcro-rad-semantic-ui#39]
After update to the latest library I found that entity picker ToOnePicker used in form pickers changed rendering from flat to button. 

Styling is a matter of personal taste, I am not complaining :-) However the change introduced visible rendering glitch on poup, where button and menu are not aligned (top-down is off by one pixel).

![image](https://user-images.githubusercontent.com/1554681/214336605-59e75b03-0397-4306-9f54-3e1de8a4f100.png)

I verified also fulcro-rad-demo and found that Category is also impacted:

![image](https://user-images.githubusercontent.com/1554681/214340406-6d8bec60-db1e-4625-b714-43d82f003d99.png)

However enumerated values State or User Role on Invoice are not :

![image](https://user-images.githubusercontent.com/1554681/214340706-d46d5675-3246-40c6-ac39-86b62fe7289f.png)

The reason is that while enumerated values use `ui active visible searach selection dropdown`, ToOnePicker wraps it with `ui small menu`

I found  the change was introduced by @holyjak in a5fa604d2de7d5c3d9c3c9decd3b46f40eecf830

https://github.com/fulcrologic/fulcro-rad-semantic-ui/blob/cb3d9051c4d8164551eacd7629257a0ce070f594/src/main/com/fulcrologic/rad/rendering/semantic_ui/entity_picker.cljc#L152

I feel that explicit override of `:marginTop` suggests that menu element is not being used with its original intent.

Suggested solution
- (if possible) use the same classes in ToOnePicker

Personally I find buttons in forms distracting but as I wrote, YMMV. Would you consider making ToOnePicker's class a parameter so one can turn it off? Thank you.

**Comment by awkay** [comment]
God I hate CSS.

I agree that all of the visual tweaks should be able to be overridden. I've fixed the merge so you can tweak that via the field style config :input/props option.

See commit 8ea240d3544e40286284bd820f4f92f351da76aa.

Deployed as 1.3.4-SNAPSHOT. Confirm that works for you and I'll cut a release.

**Comment by awkay** [comment]
And I screwed it up...just a min.

**Comment by awkay** [comment]
See 936fd0f1c5deaeb8e7520cb477cbe911615241a2.

Redeployed.

If you want to contribute a patch for the one-pixel problem, feel free. We were trying to get the darn thing to line up properly in other ways.

**Comment by holyjak** [comment]
Hi @danskarda, nice meeting you here! I believe there is special circle of hell where people have to forever try to get things aligned in CSS...

**Comment by danskarda** [comment]
> God I hate CSS.

I can related to that. 

If there was no CSS there would be flying cars. Instead we are aligning pixels...

What I learned:

- you have to wrap ui-dropdown to attach buttons 
- however any wrap I tried messes up rendering of standalone dropdown 
- you can attach buttons or fancy labels to input. However ui-dropdown is already an input with some attachments, so it is hard to attach buttons to something with attachments... So you can have A (input with attached buttons or icons) or B dropdown but not both A + B together :cry: 
- menu is not suitable for wrapping inputs and buttons together
- finally I succeeded using segments and a little bit of explicit styles (I think it looks better then menu solution).

My solution handles both cases separately:

1. Single non-mutable ui-wrapped-dropdown is rendered without wrapping container. 

![image](https://user-images.githubusercontent.com/1554681/214435017-55112bde-d06f-46e0-8972-a041e45aca62.png)

2. Mutable dropdown with additional buttons uses segments with a little bit of `{:style ...}`

![image](https://user-images.githubusercontent.com/1554681/214438378-5d9cb3c7-9ca3-438b-a6bf-1d39bd175760.png)

My solution is in a branch https://github.com/danskarda/fulcro-rad-semantic-ui/commit/65d343c37db907fb2d285a4d1c279c3ecf858a16 I tested the solution with my humble Fulcro RAD app and Fulcro RAD Demo. So please test it also on your applications. I hope it does not break anything :crossed_fingers: 
 
The victory in CSS is never 100% so there are still some glitches
![image](https://user-images.githubusercontent.com/1554681/214435502-3d09e429-da24-4c0e-8dbf-b7a7dec14874.png)

![image](https://user-images.githubusercontent.com/1554681/214435606-e8a884ea-665e-4acb-9e2f-01b906c9cdcf.png)

It seems the first one is probably caused by non-integer widths. But I do not want to die on this hill today.

**Comment by awkay** [comment]
That looks promising..I'm with you on not wanting to die on the hill :)

If you want to open a PR I'll do more testing on it and see if I find anything.

**Comment by awkay** [comment]
Fixed by #40
